version: "3.9"
services:
  frontend:
    build: ./frontend
    env_file: .env
    depends_on: [backend]
    networks: [app-net]

  backend:
    build: ./backend
    env_file: .env
    depends_on: [mongo]
    networks: [app-net]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 2s
      retries: 12

  mongo:
    image: mongo:6
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: supersecret
    volumes:
      - mongo_data:/data/db
    networks: [app-net]

  redis:
    image: redis:7-alpine
    networks: [app-net]

  nginx:
    image: nginx:1.25-alpine
    volumes:
      - ./deploy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs:/etc/nginx/certs:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on: [frontend, backend]
    networks: [app-net]

networks:
  app-net:
    driver: bridge

volumes:
  mongo_data:
